#!/usr/bin/env python3

import sys
import math

def factorize(n):
    if n % 2 == 0:
        return 2, n // 2

    for i in range(3, int(math.sqrt(n)) + 1, 2):
        if n % i == 0:
            return i, n // i

    return n, 1

def main(filename):
    with open(filename, 'r') as file:
        for line in file:
            n = int(line.strip())
            p, q = factorize(n)
            print(f"{n}={p}*{q}")

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        sys.exit(1)
    
    main(sys.argv[1])
